import type { ClosetItem } from "../../types/ClosetItem2";
import { describe, it, expect } from "vitest";
import { splitByWarmth } from "../buildOutfit2"; 


//tests splitByWarmth; generated by Claude AI 
function makeItem(id: string, warmth: number): ClosetItem {
  return {
    id,
    description: "Test item",
    type: "upper",
    layer_role: "primary",
    warmth,
    waterproof: false,
    image_url: "",
  };
}

describe("splitByWarmth", () => {
  it("puts an item exactly at the boundary into inRange, not tooLight/tooHeavy", () => {
    const items = [makeItem("a", 0.3), makeItem("b", 0.5)];
    const result = splitByWarmth(items, 0.3, 0.5);

    expect(result.in_range).toHaveLength(2);
    expect(result.too_light).toHaveLength(0);
    expect(result.too_heavy).toHaveLength(0);
  });

  it("sorts a mix of items into the correct three groups", () => {
    const blouse = makeItem("blouse", 0.2);
    const sweater = makeItem("sweater", 0.5);
    const coat = makeItem("coat", 0.9);
    const items = [blouse, sweater, coat];

    const result = splitByWarmth(items, 0.3, 0.6);

    expect(result.too_light).toEqual([blouse]);
    expect(result.in_range).toEqual([sweater]);
    expect(result.too_heavy).toEqual([coat]);
  });

  it("returns all empty arrays when given an empty item list", () => {
    const result = splitByWarmth([], 0.3, 0.5);

    expect(result.in_range).toEqual([]);
    expect(result.too_light).toEqual([]);
    expect(result.too_heavy).toEqual([]);
  });

  it("puts every item in tooHeavy when all items exceed max", () => {
    const items = [makeItem("a", 0.8), makeItem("b", 0.9)];
    const result = splitByWarmth(items, 0.1, 0.3);

    expect(result.too_heavy).toHaveLength(2);
    expect(result.in_range).toHaveLength(0);
    expect(result.too_light).toHaveLength(0);
  });

  it("puts every item in tooLight when all items are below min", () => {
    const items = [makeItem("a", 0.1), makeItem("b", 0.2)];
    const result = splitByWarmth(items, 0.5, 0.7);

    expect(result.too_light).toHaveLength(2);
    expect(result.in_range).toHaveLength(0);
    expect(result.too_heavy).toHaveLength(0);
  });
});